


export const userBlock = async (req,res,next) =>{
    try{

    }catch(err){
        console.log(err)
    }
}